name: Tests

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 14.x

      - name: Check if the repository is private
        if: ${{ github.event.repository.private }}
        run: exit 1

      - name: Clone testing library
        run: |
          set -eu
          git clone --branch main --single-branch --depth 1 https://github.com/Yandex-Practicum/tests-selfmade-project-1-public.git

      - name: Run the tests
        run: bash tests-selfmade-project-1-public/run.sh

      - name: Check if output.jpg exists
        run: ls -l tests-selfmade-project-1-public/output.jpg

      - name: Upload layout-compare
        uses: actions/upload-artifact@v3.1.0
        with:
          name: layout-compare
          path: tests-selfmade-project-1-public/output.jpg

      - name: Show test results
        run: bash tests-selfmade-project-1-public/result.sh
